#!/bin/bash

# Configure Network Adapters
sudo cat /etc/network/interfaces > /etc/network/interfaces.backup
sudo mv interfaces /etc/network/interfaces

# Static IPs on first launch
sudo ifconfig eth0 192.168.1.1/24 up
sudo ifconfig eth1 192.168.2.1/24 up
sudo systemctl restart NetworkManager

# Firewallsettings
sudo apt install ufw
sudo ./firewallsettings.sh
